# Multi-ML-Framework Sample Training

This notebook demonstrates the orchestration shape for training different model families on the same Quant Warehouse dataset. The universe is MAG7 and the data vendors are `yfinance` and `fmp`; the ML frameworks are RAPIDS cuML RandomForest, PyTorch, and FlairNLP with a tiny pretrained transformer.

All market data, numeric features, and optimal-trade targets come from Quant Warehouse. The notebook does not write temporary CSV or parquet data files.

In [1]:
from __future__ import annotations

from pathlib import Path
from time import perf_counter
import math
import random
import sys
import warnings

import numpy as np
import pandas as pd
from IPython.display import Markdown, display

def find_repo_root(start: Path) -> Path:
    for candidate in (start.resolve(), *start.resolve().parents):
        if (candidate / "pyproject.toml").exists() and (candidate / "quant_orchestrator").exists():
            return candidate
    raise RuntimeError(f"Could not find quant-orchestrator repo root from {start}")


REPO_ROOT = find_repo_root(Path.cwd())
for path in (REPO_ROOT, REPO_ROOT.parent / "quant-warehouse"):
    if path.exists() and str(path) not in sys.path:
        sys.path.insert(0, str(path))

warnings.filterwarnings("ignore", category=UserWarning)

from quant_warehouse import Warehouse
from quant_warehouse.target_engineering import build_label_panel

from sklearn.metrics import accuracy_score, f1_score, mean_absolute_error, roc_auc_score
from sklearn.preprocessing import StandardScaler

import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

import flair
from quant_orchestrator.platforms.ml_frameworks.flair.shared import (
    predict_classification_regression,
    train_classification_regression_multitask,
)

In [2]:
SYMBOLS = ["AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "TSLA"]
PROVIDERS = ("yfinance", "fmp")
START = "2020-01-01"
END = None
OHLCV_COLUMNS = ["open", "high", "low", "close", "volume"]
LABEL_K_PARAMS = {"YE": list(range(1, 13))}
TRAIN_END = pd.Timestamp("2024-12-31")
DEV_END = pd.Timestamp("2025-12-31")
RANDOM_SEED = 20260629
TORCH_EPOCHS = 20
FLAIR_EPOCHS = 1
FLAIR_TRANSFORMER = "prajjwal1/bert-tiny"
ARTIFACT_DIR = REPO_ROOT / "artifacts" / "notebooks" / "mult-ml-frameworks"
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(RANDOM_SEED)

TORCH_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
flair.device = TORCH_DEVICE

runtime_config = pd.DataFrame(
    [
        {"setting": "symbols", "value": ", ".join(SYMBOLS)},
        {"setting": "providers", "value": ", ".join(PROVIDERS)},
        {"setting": "date_range", "value": f"{START} to latest warehouse row"},
        {"setting": "target_engineering", "value": f"optimal_trading {LABEL_K_PARAMS}"},
        {"setting": "torch_cuda_available", "value": torch.cuda.is_available()},
        {"setting": "torch_device", "value": str(TORCH_DEVICE)},
        {"setting": "flair_transformer", "value": FLAIR_TRANSFORMER},
    ]
)
display(runtime_config)

                setting                                              value
0               symbols          AAPL, MSFT, NVDA, AMZN, META, GOOGL, TSLA
1             providers                                      yfinance, fmp
2            date_range                 2020-01-01 to latest warehouse row
3    target_engineering  optimal_trading {'YE': [1, 2, 3, 4, 5, 6, 7, 8...
4  torch_cuda_available                                               True
5          torch_device                                               cuda
6     flair_transformer                                prajjwal1/bert-tiny

## Dataset Construction

Each provider gets an independent MAG7 dataset. The numeric feature matrix is adjusted OHLCV from Quant Warehouse. The binary label and return percentile target are generated by Quant Warehouse target engineering with one optimal-trading label configuration: `YE: 1..12`.

In [3]:
def normalize_price_frame(prices: pd.DataFrame) -> pd.DataFrame:
    frame = prices.copy()
    frame.columns = [str(col).lower() for col in frame.columns]
    frame.index = pd.to_datetime(frame.index).tz_localize(None)
    frame = frame.sort_index()
    missing = [col for col in OHLCV_COLUMNS if col not in frame.columns]
    if missing:
        raise ValueError(f"Missing OHLCV columns from warehouse prices: {missing}")
    return frame[OHLCV_COLUMNS].astype(float).dropna()


def row_to_key_value_text(row: pd.Series) -> str:
    return " ".join(
        [
            f"symbol={row['symbol']}",
            f"provider={row['provider']}",
            f"datetime={pd.Timestamp(row['date']).date()}",
            f"event={row.get('event', 'label')}",
            f"horizon={row.get('horizon', 'unknown')}",
            f"open={row['open']:.6f}",
            f"high={row['high']:.6f}",
            f"low={row['low']:.6f}",
            f"close={row['close']:.6f}",
            f"volume={row['volume']:.0f}",
        ]
    )



def load_provider_dataset(provider: str) -> pd.DataFrame:
    provider_frames = []
    for symbol in SYMBOLS:
        prices = normalize_price_frame(Warehouse().read_prices(symbol, provider=provider, start=START, end=END))
        labels = build_label_panel(
            {symbol: prices.copy()},
            k_params=LABEL_K_PARAMS,
            solver_mode="period_top_k",
            add_rank_labels=True,
            deduplicate=True,
            max_workers=1,
        ).reset_index()
        labels["date"] = pd.to_datetime(labels["date"]).dt.tz_localize(None)
        labels["symbol"] = labels["symbol"].astype(str)
        labels = labels.dropna(subset=["date", "symbol", "target", "rank_y"]).copy()
        labels["target"] = labels["target"].astype(int)
        labels["rank_y"] = labels["rank_y"].astype(float)

        symbol_prices = prices.reset_index().rename(columns={"index": "date"})
        symbol_prices["symbol"] = symbol
        symbol_dataset = labels.merge(symbol_prices, on=["date", "symbol"], how="inner")
        symbol_dataset["provider"] = provider
        provider_frames.append(symbol_dataset)

    dataset = pd.concat(provider_frames, ignore_index=True).sort_values(
        ["symbol", "date", "event", "horizon"]
    )
    dataset["text"] = dataset.apply(row_to_key_value_text, axis=1)
    dataset = dataset.reset_index(drop=True)
    if dataset["target"].nunique() < 2:
        raise ValueError(f"{provider} dataset has only one class after joining features and labels")
    return dataset


def chronological_split(dataset: pd.DataFrame) -> dict[str, pd.DataFrame]:
    train = dataset[dataset["date"] <= TRAIN_END].copy()
    dev = dataset[(dataset["date"] > TRAIN_END) & (dataset["date"] <= DEV_END)].copy()
    test = dataset[dataset["date"] > DEV_END].copy()
    if min(len(train), len(dev), len(test)) == 0:
        ordered = dataset.sort_values("date").reset_index(drop=True)
        first = max(2, int(len(ordered) * 0.70))
        second = max(first + 1, int(len(ordered) * 0.85))
        train = ordered.iloc[:first].copy()
        dev = ordered.iloc[first:second].copy()
        test = ordered.iloc[second:].copy()
    return {"train": train, "dev": dev, "test": test}


def scaled_feature_splits(splits: dict[str, pd.DataFrame]) -> tuple[dict[str, np.ndarray], StandardScaler]:
    scaler = StandardScaler()
    arrays = {
        "train": scaler.fit_transform(splits["train"][OHLCV_COLUMNS]).astype("float32"),
        "dev": scaler.transform(splits["dev"][OHLCV_COLUMNS]).astype("float32"),
        "test": scaler.transform(splits["test"][OHLCV_COLUMNS]).astype("float32"),
    }
    return arrays, scaler

In [4]:
provider_datasets = {}
provider_splits = {}
provider_arrays = {}
provider_scalers = {}
audit_rows = []

for provider in PROVIDERS:
    dataset = load_provider_dataset(provider)
    splits = chronological_split(dataset)
    arrays, scaler = scaled_feature_splits(splits)
    provider_datasets[provider] = dataset
    provider_splits[provider] = splits
    provider_arrays[provider] = arrays
    provider_scalers[provider] = scaler
    audit_rows.append(
        {
            "provider": provider,
            "symbols": dataset["symbol"].nunique(),
            "rows": len(dataset),
            "train_rows": len(splits["train"]),
            "dev_rows": len(splits["dev"]),
            "test_rows": len(splits["test"]),
            "positive_rate": dataset["target"].mean(),
            "first_label_date": dataset["date"].min().date(),
            "last_label_date": dataset["date"].max().date(),
            "unique_horizons": dataset["horizon"].nunique(),
        }
    )

summary = pd.DataFrame(audit_rows)
display(summary)

display(Markdown("### Sample Rows"))
preview_cols = ["provider", "date", "symbol", "open", "high", "low", "close", "volume", "target", "rank_y", "event", "horizon"]
display(pd.concat([provider_datasets[p].head(3) for p in PROVIDERS], ignore_index=True)[preview_cols])

,provider,symbols,rows,train_rows,dev_rows,test_rows,positive_rate,first_label_date,last_label_date,unique_horizons
0,yfinance,7,1405,1011,204,190,0.503915,2020-01-02,2026-06-26,12
1,fmp,7,1403,1012,204,187,0.504633,2020-01-02,2026-06-24,12

### Sample Rows

,provider,date,symbol,open,high,low,close,volume,target,rank_y,event,horizon
0,yfinance,2020-01-06,AAPL,70.754014,72.239942,70.503546,72.201408,118387200.0,1,0.302030,entry,YE_k7
1,yfinance,2020-01-29,AAPL,78.137915,78.956742,77.398559,78.111420,216229200.0,0,0.243655,exit,YE_k12
2,yfinance,2020-02-03,AAPL,73.285151,75.498397,72.784224,74.335182,173788400.0,1,0.106599,entry,YE_k12
3,fmp,2020-01-06,AAPL,70.750000,72.230000,70.490000,72.190000,118578576.0,1,0.305128,entry,YE_k8
4,fmp,2020-01-29,AAPL,78.130000,78.950000,77.400000,78.100000,216599712.0,0,0.246154,exit,YE_k12
5,fmp,2020-02-03,AAPL,73.280000,75.490000,72.780000,74.330000,173985604.0,1,0.102564,entry,YE_k12

## Model Training Helpers

The RandomForest is a scikit-learn style model trained with RAPIDS cuML on CUDA. The autoencoder is a PyTorch CUDA model. The Flair model uses a tiny pretrained transformer and Flair's `MultitaskModel` for classification plus return-percentile regression.

In [5]:
def train_cuml_random_forest(provider: str, splits: dict[str, pd.DataFrame], arrays: dict[str, np.ndarray]) -> dict[str, object]:
    import cudf
    from cuml.ensemble import RandomForestClassifier

    started = perf_counter()
    model = RandomForestClassifier(
        n_estimators=128,
        max_depth=8,
        random_state=RANDOM_SEED,
        n_streams=1,
    )
    x_train = cudf.DataFrame(pd.DataFrame(arrays["train"], columns=OHLCV_COLUMNS))
    y_train = cudf.Series(splits["train"]["target"].astype("int32").reset_index(drop=True))
    model.fit(x_train, y_train)

    x_test = cudf.DataFrame(pd.DataFrame(arrays["test"], columns=OHLCV_COLUMNS))
    y_test = splits["test"]["target"].astype(int).to_numpy()
    pred = model.predict(x_test).to_numpy().astype(int)
    proba_raw = model.predict_proba(x_test)
    proba = proba_raw.to_numpy()[:, 1] if hasattr(proba_raw, "to_numpy") else np.asarray(proba_raw)[:, 1]
    elapsed = perf_counter() - started
    return {
        "provider": provider,
        "framework": "sklearn API via RAPIDS cuML",
        "model": "RandomForestClassifier",
        "device": "cuda",
        "test_accuracy": accuracy_score(y_test, pred),
        "test_f1": f1_score(y_test, pred, zero_division=0),
        "test_roc_auc": roc_auc_score(y_test, proba) if len(np.unique(y_test)) == 2 else np.nan,
        "test_mae": np.nan,
        "train_seconds": elapsed,
    }


class TinyAutoencoder(nn.Module):
    def __init__(self, input_dim: int, latent_dim: int = 3):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(input_dim, 8), nn.ReLU(), nn.Linear(8, latent_dim))
        self.decoder = nn.Sequential(nn.Linear(latent_dim, 8), nn.ReLU(), nn.Linear(8, input_dim))

    def forward(self, values: torch.Tensor) -> torch.Tensor:
        return self.decoder(self.encoder(values))


def train_torch_autoencoder(provider: str, arrays: dict[str, np.ndarray]) -> dict[str, object]:
    started = perf_counter()
    model = TinyAutoencoder(input_dim=len(OHLCV_COLUMNS)).to(TORCH_DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
    loss_fn = nn.MSELoss()
    train_tensor = torch.tensor(arrays["train"], dtype=torch.float32)
    loader = DataLoader(TensorDataset(train_tensor), batch_size=32, shuffle=True)
    for _ in range(TORCH_EPOCHS):
        model.train()
        for (batch,) in loader:
            batch = batch.to(TORCH_DEVICE)
            optimizer.zero_grad(set_to_none=True)
            loss = loss_fn(model(batch), batch)
            loss.backward()
            optimizer.step()
    model.eval()
    with torch.no_grad():
        train_x = torch.tensor(arrays["train"], dtype=torch.float32, device=TORCH_DEVICE)
        test_x = torch.tensor(arrays["test"], dtype=torch.float32, device=TORCH_DEVICE)
        train_mse = loss_fn(model(train_x), train_x).detach().cpu().item()
        test_mse = loss_fn(model(test_x), test_x).detach().cpu().item()
    elapsed = perf_counter() - started
    return {
        "provider": provider,
        "framework": "PyTorch",
        "model": "TinyAutoencoder",
        "device": str(TORCH_DEVICE),
        "test_accuracy": np.nan,
        "test_f1": np.nan,
        "test_roc_auc": np.nan,
        "test_mae": np.nan,
        "train_reconstruction_mse": train_mse,
        "test_reconstruction_mse": test_mse,
        "train_seconds": elapsed,
    }

In [6]:
def train_flair_multitask(provider: str, splits: dict[str, pd.DataFrame]) -> dict[str, object]:
    started = perf_counter()
    result = train_classification_regression_multitask(
        splits,
        base_path=ARTIFACT_DIR / f"flair_mtl_{provider}",
        transformer_model=FLAIR_TRANSFORMER,
        text_column="text",
        classification_column="target",
        regression_column="rank_y",
        class_label_fn=lambda value: "long" if int(value) == 1 else "not_long",
        classification_label_type="direction",
        regression_label_type="return_percentile",
        classification_task_id="direction",
        regression_task_id="return_percentile",
        classification_loss_factor=1.0,
        regression_loss_factor=0.5,
        fine_tune_transformer=False,
        max_epochs=FLAIR_EPOCHS,
        learning_rate=1e-4,
        mini_batch_size=16,
        mini_batch_chunk_size=8,
        eval_batch_size=32,
        save_final_model=False,
        create_file_logs=False,
        create_loss_file=False,
        embeddings_storage_mode="none",
    )
    y_pred_direction_labels, y_pred_return = predict_classification_regression(
        result,
        result.corpus.test,
        classification_prediction_label="pred_direction",
        regression_prediction_label="pred_return_percentile",
        mini_batch_size=32,
    )
    y_true_direction = splits["test"]["target"].astype(int).to_numpy()
    y_pred_direction = np.array([1 if label == "long" else 0 for label in y_pred_direction_labels])
    y_true_return = splits["test"]["rank_y"].astype(float).to_numpy()
    elapsed = perf_counter() - started
    return {
        "provider": provider,
        "framework": "FlairNLP",
        "model": f"MultitaskModel({FLAIR_TRANSFORMER})",
        "device": str(TORCH_DEVICE),
        "test_accuracy": accuracy_score(y_true_direction, y_pred_direction),
        "test_f1": f1_score(y_true_direction, y_pred_direction, zero_division=0),
        "test_roc_auc": np.nan,
        "test_mae": mean_absolute_error(y_true_return, y_pred_return),
        "train_seconds": elapsed,
    }

In [7]:
results = []
for provider in PROVIDERS:
    display(Markdown(f"### Training models for `{provider}`"))
    splits = provider_splits[provider]
    arrays = provider_arrays[provider]
    for trainer in (train_cuml_random_forest, train_torch_autoencoder, train_flair_multitask):
        if trainer is train_cuml_random_forest:
            row = trainer(provider, splits, arrays)
        elif trainer is train_torch_autoencoder:
            row = trainer(provider, arrays)
        else:
            row = trainer(provider, splits)
        results.append(row)
        display(pd.DataFrame([row]).dropna(axis=1, how="all"))

results_df = pd.DataFrame(results)
metric_cols = [
    "provider",
    "framework",
    "model",
    "device",
    "test_accuracy",
    "test_f1",
    "test_roc_auc",
    "test_mae",
    "train_reconstruction_mse",
    "test_reconstruction_mse",
    "train_seconds",
]
results_df = results_df.reindex(columns=metric_cols)
display(Markdown("## Cross-Provider / Cross-Framework Results"))
display(results_df)

### Training models for `yfinance`

[06:58:24] /__w/nvforest/nvforest/python/nvforest/build/cp311-abi3-linux_aarch64/_deps/treelite-src/src/serializer.cc:202: The model you are loading originated from a newer Treelite version; some functionalities may be unavailable.
Currently running Treelite version 4.6.1
The model checkpoint was generated from Treelite version 4.7.0

,provider,framework,model,device,test_accuracy,test_f1,test_roc_auc,train_seconds
0,yfinance,sklearn API via RAPIDS cuML,RandomForestClassifier,cuda,0.442105,0.302632,0.486919,2.310369

,provider,framework,model,device,train_reconstruction_mse,test_reconstruction_mse,train_seconds
0,yfinance,PyTorch,TinyAutoencoder,cuda,0.043987,0.020841,1.347633

2026-06-29 06:58:27,911 Computing label dictionary. Progress:

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

1011it [00:00, 157303.90it/s]

2026-06-29 06:58:27,923 Dictionary created for label 'direction' with 2 values: long (seen 510 times), not_long (seen 501 times)

2026-06-29 06:58:27,925 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,926 Model: "MultitaskModel(
  (direction): TextClassifier(
    (embeddings): TransformerDocumentEmbeddings(
      (model): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30523, 128, padding_idx=0)
          (position_embeddings): Embedding(512, 128)
          (token_type_embeddings): Embedding(2, 128)
          (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-1): 2 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): Linear(in_features=128, out_features=128, bias=True)
                  (key): Linear(in_features=128, out_features=128, bias=True)
                  (value): Linear(in_features=128, out_features=128, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=128, out_features=128, bias=True)
                  (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=128, out_features=512, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=512, out_features=128, bias=True)
                (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=128, out_features=128, bias=True)
          (activation): Tanh()
        )
      )
    )
    (decoder): Linear(in_features=128, out_features=2, bias=True)
    (dropout): Dropout(p=0.0, inplace=False)
    (locked_dropout): LockedDropout(p=0.0)
    (word_dropout): WordDropout(p=0.0)
    (loss_function): CrossEntropyLoss()
  )
  (return_percentile): TextRegressor(
    (document_embeddings): TransformerDocumentEmbeddings(
      (model): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30523, 128, padding_idx=0)
          (position_embeddings): Embedding(512, 128)
          (token_type_embeddings): Embedding(2, 128)
          (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-1): 2 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): Linear(in_features=128, out_features=128, bias=True)
                  (key): Linear(in_features=128, out_features=128, bias=True)
                  (value): Linear(in_features=128, out_features=128, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=128, out_features=128, bias=True)
                  (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=128, out_features=512, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=512, out_features=128, bias=True)
                (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=128, out_features=128, bias=True)
          (activation): Tanh()
        )
      )
    )
    (decoder): Linear(in_features=128, out_features=1, bias=True)
    (loss_function): MSELoss()
  )
)"

2026-06-29 06:58:27,927 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,927 Corpus: 1011 train + 204 dev + 190 test sentences

2026-06-29 06:58:27,927 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,928 Train:  1011 sentences

2026-06-29 06:58:27,928         (train_with_dev=False, train_with_test=False)

2026-06-29 06:58:27,928 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,928 Training Params:

2026-06-29 06:58:27,929  - learning_rate: "0.0001"

2026-06-29 06:58:27,929  - mini_batch_size: "16"

2026-06-29 06:58:27,929  - max_epochs: "1"

2026-06-29 06:58:27,929  - shuffle: "True"

2026-06-29 06:58:27,930 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,930 Plugins:

2026-06-29 06:58:27,930  - LinearScheduler | warmup_fraction: '0.1'

2026-06-29 06:58:27,930 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,931 Final evaluation on model after last epoch (final-model.pt)

2026-06-29 06:58:27,931  - metric: "('micro avg', 'f1-score')"

2026-06-29 06:58:27,932 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,933 Computation:

2026-06-29 06:58:27,933  - compute on device: cuda

2026-06-29 06:58:27,933  - embedding storage: none

2026-06-29 06:58:27,933 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,934 Model training base path: "/home/jlee153232/PycharmProjects/quant-orchestrator/artifacts/notebooks/mult-ml-frameworks/flair_mtl_yfinance"

2026-06-29 06:58:27,934 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:27,934 ----------------------------------------------------------------------------------------------------

/home/jlee153232/miniconda3/envs/quant-orchestrator/lib/python3.12/site-packages/flair/trainers/trainer.py:545: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp and flair.device.type != "cpu")

2026-06-29 06:58:28,207 epoch 1 - iter 6/64 - loss 0.54312464 - time (sec): 0.27 - samples/sec: 704.70 - lr: 0.000083 - momentum: 0.000000

2026-06-29 06:58:28,256 epoch 1 - iter 12/64 - loss 0.53793435 - time (sec): 0.32 - samples/sec: 1197.61 - lr: 0.000091 - momentum: 0.000000

2026-06-29 06:58:28,299 epoch 1 - iter 18/64 - loss 0.53270777 - time (sec): 0.36 - samples/sec: 1579.98 - lr: 0.000081 - momentum: 0.000000

2026-06-29 06:58:28,343 epoch 1 - iter 24/64 - loss 0.53825879 - time (sec): 0.41 - samples/sec: 1880.73 - lr: 0.000071 - momentum: 0.000000

2026-06-29 06:58:28,389 epoch 1 - iter 30/64 - loss 0.53383374 - time (sec): 0.45 - samples/sec: 2112.89 - lr: 0.000060 - momentum: 0.000000

2026-06-29 06:58:28,430 epoch 1 - iter 36/64 - loss 0.53699755 - time (sec): 0.50 - samples/sec: 2324.86 - lr: 0.000050 - momentum: 0.000000

2026-06-29 06:58:28,472 epoch 1 - iter 42/64 - loss 0.52627113 - time (sec): 0.54 - samples/sec: 2502.31 - lr: 0.000040 - momentum: 0.000000

2026-06-29 06:58:28,515 epoch 1 - iter 48/64 - loss 0.52208860 - time (sec): 0.58 - samples/sec: 2648.52 - lr: 0.000029 - momentum: 0.000000

2026-06-29 06:58:28,561 epoch 1 - iter 54/64 - loss 0.52151515 - time (sec): 0.63 - samples/sec: 2759.11 - lr: 0.000019 - momentum: 0.000000

2026-06-29 06:58:28,609 epoch 1 - iter 60/64 - loss 0.52494804 - time (sec): 0.67 - samples/sec: 2849.85 - lr: 0.000009 - momentum: 0.000000

2026-06-29 06:58:28,638 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:28,639 EPOCH 1 done: loss 0.5276 - lr: 0.000009

  0%|          | 0/7 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:00<00:00, 138.60it/s]

2026-06-29 06:58:28,733 DEV : loss 0.4142088294029236 - f1-score (micro avg)  0.2892

2026-06-29 06:58:28,734 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:28,735 Testing using last state of model ...

  0%|          | 0/6 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 168.04it/s]

2026-06-29 06:58:28,810 --------------------------------------------------

direction - Label type: direction


Results:
- F-score (micro) 0.4895
- F-score (macro) 0.3828
- Accuracy 0.4895

By class:
              precision    recall  f1-score   support

    not_long     0.4886    0.9247    0.6394        93
        long     0.5000    0.0722    0.1261        97

    accuracy                         0.4895       190
   macro avg     0.4943    0.4984    0.3828       190
weighted avg     0.4944    0.4895    0.3774       190
--------------------------------------------------

return_percentile - Label type: return_percentile

AVG: mse: 0.1009 - mae: 0.2718 - pearson: 0.0048 - spearman: -0.0054

2026-06-29 06:58:28,810 ----------------------------------------------------------------------------------------------------

,provider,framework,model,device,test_accuracy,test_f1,test_mae,train_seconds
0,yfinance,FlairNLP,MultitaskModel(prajjwal1/bert-tiny),cuda,0.489474,0.126126,0.271794,2.489784

### Training models for `fmp`

[06:58:29] /__w/nvforest/nvforest/python/nvforest/build/cp311-abi3-linux_aarch64/_deps/treelite-src/src/serializer.cc:202: The model you are loading originated from a newer Treelite version; some functionalities may be unavailable.
Currently running Treelite version 4.6.1
The model checkpoint was generated from Treelite version 4.7.0

,provider,framework,model,device,test_accuracy,test_f1,test_roc_auc,train_seconds
0,fmp,sklearn API via RAPIDS cuML,RandomForestClassifier,cuda,0.524064,0.410596,0.554258,0.312385

,provider,framework,model,device,train_reconstruction_mse,test_reconstruction_mse,train_seconds
0,fmp,PyTorch,TinyAutoencoder,cuda,0.020801,0.034507,0.816645

2026-06-29 06:58:31,515 Computing label dictionary. Progress:

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

1012it [00:00, 161916.29it/s]

2026-06-29 06:58:31,526 Dictionary created for label 'direction' with 2 values: long (seen 511 times), not_long (seen 501 times)

2026-06-29 06:58:31,529 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,529 Model: "MultitaskModel(
  (direction): TextClassifier(
    (embeddings): TransformerDocumentEmbeddings(
      (model): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30523, 128, padding_idx=0)
          (position_embeddings): Embedding(512, 128)
          (token_type_embeddings): Embedding(2, 128)
          (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-1): 2 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): Linear(in_features=128, out_features=128, bias=True)
                  (key): Linear(in_features=128, out_features=128, bias=True)
                  (value): Linear(in_features=128, out_features=128, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=128, out_features=128, bias=True)
                  (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=128, out_features=512, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=512, out_features=128, bias=True)
                (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=128, out_features=128, bias=True)
          (activation): Tanh()
        )
      )
    )
    (decoder): Linear(in_features=128, out_features=2, bias=True)
    (dropout): Dropout(p=0.0, inplace=False)
    (locked_dropout): LockedDropout(p=0.0)
    (word_dropout): WordDropout(p=0.0)
    (loss_function): CrossEntropyLoss()
  )
  (return_percentile): TextRegressor(
    (document_embeddings): TransformerDocumentEmbeddings(
      (model): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30523, 128, padding_idx=0)
          (position_embeddings): Embedding(512, 128)
          (token_type_embeddings): Embedding(2, 128)
          (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-1): 2 x BertLayer(
              (attention): BertAttention(
                (self): BertSdpaSelfAttention(
                  (query): Linear(in_features=128, out_features=128, bias=True)
                  (key): Linear(in_features=128, out_features=128, bias=True)
                  (value): Linear(in_features=128, out_features=128, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=128, out_features=128, bias=True)
                  (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=128, out_features=512, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): BertOutput(
                (dense): Linear(in_features=512, out_features=128, bias=True)
                (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=128, out_features=128, bias=True)
          (activation): Tanh()
        )
      )
    )
    (decoder): Linear(in_features=128, out_features=1, bias=True)
    (loss_function): MSELoss()
  )
)"

2026-06-29 06:58:31,530 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,530 Corpus: 1012 train + 204 dev + 187 test sentences

2026-06-29 06:58:31,530 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,530 Train:  1012 sentences

2026-06-29 06:58:31,531         (train_with_dev=False, train_with_test=False)

2026-06-29 06:58:31,531 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,531 Training Params:

2026-06-29 06:58:31,531  - learning_rate: "0.0001"

2026-06-29 06:58:31,531  - mini_batch_size: "16"

2026-06-29 06:58:31,532  - max_epochs: "1"

2026-06-29 06:58:31,532  - shuffle: "True"

2026-06-29 06:58:31,532 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,532 Plugins:

2026-06-29 06:58:31,533  - LinearScheduler | warmup_fraction: '0.1'

2026-06-29 06:58:31,533 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,533 Final evaluation on model after last epoch (final-model.pt)

2026-06-29 06:58:31,534  - metric: "('micro avg', 'f1-score')"

2026-06-29 06:58:31,534 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,534 Computation:

2026-06-29 06:58:31,534  - compute on device: cuda

2026-06-29 06:58:31,535  - embedding storage: none

2026-06-29 06:58:31,535 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,535 Model training base path: "/home/jlee153232/PycharmProjects/quant-orchestrator/artifacts/notebooks/mult-ml-frameworks/flair_mtl_fmp"

2026-06-29 06:58:31,535 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,536 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,576 epoch 1 - iter 6/64 - loss 0.69612206 - time (sec): 0.04 - samples/sec: 4803.87 - lr: 0.000083 - momentum: 0.000000

2026-06-29 06:58:31,613 epoch 1 - iter 12/64 - loss 0.66944039 - time (sec): 0.08 - samples/sec: 5023.18 - lr: 0.000091 - momentum: 0.000000

2026-06-29 06:58:31,648 epoch 1 - iter 18/64 - loss 0.67595971 - time (sec): 0.11 - samples/sec: 5151.36 - lr: 0.000081 - momentum: 0.000000

2026-06-29 06:58:31,682 epoch 1 - iter 24/64 - loss 0.66701335 - time (sec): 0.15 - samples/sec: 5259.17 - lr: 0.000071 - momentum: 0.000000

/home/jlee153232/miniconda3/envs/quant-orchestrator/lib/python3.12/site-packages/flair/trainers/trainer.py:545: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp and flair.device.type != "cpu")

2026-06-29 06:58:31,727 epoch 1 - iter 30/64 - loss 0.64798106 - time (sec): 0.19 - samples/sec: 5033.19 - lr: 0.000060 - momentum: 0.000000

2026-06-29 06:58:31,770 epoch 1 - iter 36/64 - loss 0.62473735 - time (sec): 0.23 - samples/sec: 4933.76 - lr: 0.000050 - momentum: 0.000000

2026-06-29 06:58:31,815 epoch 1 - iter 42/64 - loss 0.62310898 - time (sec): 0.28 - samples/sec: 4811.39 - lr: 0.000040 - momentum: 0.000000

2026-06-29 06:58:31,855 epoch 1 - iter 48/64 - loss 0.61322184 - time (sec): 0.32 - samples/sec: 4817.23 - lr: 0.000029 - momentum: 0.000000

2026-06-29 06:58:31,897 epoch 1 - iter 54/64 - loss 0.60713741 - time (sec): 0.36 - samples/sec: 4792.07 - lr: 0.000019 - momentum: 0.000000

2026-06-29 06:58:31,938 epoch 1 - iter 60/64 - loss 0.60152597 - time (sec): 0.40 - samples/sec: 4778.50 - lr: 0.000009 - momentum: 0.000000

2026-06-29 06:58:31,958 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:31,958 EPOCH 1 done: loss 0.5987 - lr: 0.000009

  0%|          | 0/7 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:00<00:00, 176.99it/s]

2026-06-29 06:58:32,041 DEV : loss 0.6750449538230896 - f1-score (micro avg)  0.1963

2026-06-29 06:58:32,042 ----------------------------------------------------------------------------------------------------

2026-06-29 06:58:32,043 Testing using last state of model ...

  0%|          | 0/6 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 170.18it/s]

2026-06-29 06:58:32,117 --------------------------------------------------

direction - Label type: direction


Results:
- F-score (micro) 0.4385
- F-score (macro) 0.4169
- Accuracy 0.4385

By class:
              precision    recall  f1-score   support

    not_long     0.4470    0.6484    0.5291        91
        long     0.4182    0.2396    0.3046        96

    accuracy                         0.4385       187
   macro avg     0.4326    0.4440    0.4169       187
weighted avg     0.4322    0.4385    0.4139       187
--------------------------------------------------

return_percentile - Label type: return_percentile

AVG: mse: 1.0194 - mae: 0.9517 - pearson: -0.1464 - spearman: -0.1253

2026-06-29 06:58:32,118 ----------------------------------------------------------------------------------------------------

,provider,framework,model,device,test_accuracy,test_f1,test_mae,train_seconds
0,fmp,FlairNLP,MultitaskModel(prajjwal1/bert-tiny),cuda,0.438503,0.304636,0.951664,2.163644

## Cross-Provider / Cross-Framework Results

,provider,framework,model,device,test_accuracy,test_f1,test_roc_auc,test_mae,train_reconstruction_mse,test_reconstruction_mse,train_seconds
0,yfinance,sklearn API via RAPIDS cuML,RandomForestClassifier,cuda,0.442105,0.302632,0.486919,NaN,NaN,NaN,2.310369
1,yfinance,PyTorch,TinyAutoencoder,cuda,NaN,NaN,NaN,NaN,0.043987,0.020841,1.347633
2,yfinance,FlairNLP,MultitaskModel(prajjwal1/bert-tiny),cuda,0.489474,0.126126,NaN,0.271794,NaN,NaN,2.489784
3,fmp,sklearn API via RAPIDS cuML,RandomForestClassifier,cuda,0.524064,0.410596,0.554258,NaN,NaN,NaN,0.312385
4,fmp,PyTorch,TinyAutoencoder,cuda,NaN,NaN,NaN,NaN,0.020801,0.034507,0.816645
5,fmp,FlairNLP,MultitaskModel(prajjwal1/bert-tiny),cuda,0.438503,0.304636,NaN,0.951664,NaN,NaN,2.163644

In [8]:
readable = results_df.copy()
for col in ["test_accuracy", "test_f1", "test_roc_auc", "test_mae", "train_reconstruction_mse", "test_reconstruction_mse", "train_seconds"]:
    readable[col] = pd.to_numeric(readable[col], errors="coerce").round(4)

rf_rows = readable[readable["framework"].str.contains("cuML", na=False)].sort_values("test_f1", ascending=False)
flair_rows = readable[readable["framework"].eq("FlairNLP")].sort_values("test_f1", ascending=False)
torch_rows = readable[readable["framework"].eq("PyTorch")].sort_values("test_reconstruction_mse", ascending=True)

lines = [
    "## Notebook Readout",
    f"- Quant Warehouse produced {int(summary['rows'].sum())} labeled rows across {len(PROVIDERS)} data vendors and {len(SYMBOLS)} symbols.",
]
if not rf_rows.empty:
    best = rf_rows.iloc[0]
    lines.append(
        f"- Best CUDA RandomForest classification run: {best['provider']} with F1={best['test_f1']} and ROC AUC={best['test_roc_auc']}."
    )
if not flair_rows.empty:
    best = flair_rows.iloc[0]
    lines.append(
        f"- Best tiny-transformer Flair direction run: {best['provider']} with F1={best['test_f1']} and return-percentile MAE={best['test_mae']}."
    )
if not torch_rows.empty:
    best = torch_rows.iloc[0]
    lines.append(
        f"- Best PyTorch autoencoder reconstruction run: {best['provider']} with test MSE={best['test_reconstruction_mse']}."
    )
lines.append(
    "- This is intentionally a toy training notebook: it validates data movement, CUDA selection, framework differences, and target reuse before platform abstractions are tightened."
)
display(Markdown("\n".join(lines)))
display(readable)

## Notebook Readout
- Quant Warehouse produced 2808 labeled rows across 2 data vendors and 7 symbols.
- Best CUDA RandomForest classification run: fmp with F1=0.4106 and ROC AUC=0.5543.
- Best tiny-transformer Flair direction run: fmp with F1=0.3046 and return-percentile MAE=0.9517.
- Best PyTorch autoencoder reconstruction run: yfinance with test MSE=0.0208.
- This is intentionally a toy training notebook: it validates data movement, CUDA selection, framework differences, and target reuse before platform abstractions are tightened.

,provider,framework,model,device,test_accuracy,test_f1,test_roc_auc,test_mae,train_reconstruction_mse,test_reconstruction_mse,train_seconds
0,yfinance,sklearn API via RAPIDS cuML,RandomForestClassifier,cuda,0.4421,0.3026,0.4869,NaN,NaN,NaN,2.3104
1,yfinance,PyTorch,TinyAutoencoder,cuda,NaN,NaN,NaN,NaN,0.0440,0.0208,1.3476
2,yfinance,FlairNLP,MultitaskModel(prajjwal1/bert-tiny),cuda,0.4895,0.1261,NaN,0.2718,NaN,NaN,2.4898
3,fmp,sklearn API via RAPIDS cuML,RandomForestClassifier,cuda,0.5241,0.4106,0.5543,NaN,NaN,NaN,0.3124
4,fmp,PyTorch,TinyAutoencoder,cuda,NaN,NaN,NaN,NaN,0.0208,0.0345,0.8166
5,fmp,FlairNLP,MultitaskModel(prajjwal1/bert-tiny),cuda,0.4385,0.3046,NaN,0.9517,NaN,NaN,2.1636